### ISSUE TITLE
hostname inside link text with formatting is wrongly autolinked

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/mdast-util-gfm-autolink-literal#1]
### Subject of the issue

Consider the following markdown:

```
[**www.richardianson.com**](https://richardianson.com/)
```

which renders correctly on github:
[**www.richardianson.com**](https://richardianson.com/)

but with `mdast-util-gfm-autolink-literal`, it parses to:

```
root[1] (1:1-1:56, 0-55)
└─0 paragraph[2] (1:1-1:56, 0-55)
    ├─0 text "[**" (1:1-1:4, 0-3)
    └─1 link[1] (1:4-1:56, 3-55)
        │ title: null
        │ url: "http://www.richardianson.com**](https://richardianson.com/)"
        └─0 text "www.richardianson.com**](https://richardianson.com/)" (1:4-1:56, 3-55)
```

instead of:

```
root[1] (1:1-1:56, 0-55)
└─0 paragraph[1] (1:1-1:56, 0-55)
    └─0 link[1] (1:1-1:56, 0-55)
        │ title: null
        │ url: "https://richardianson.com/"
        └─0 strong[1] (1:2-1:27, 1-26)
            └─0 text "www.richardianson.com" (1:4-1:25, 3-24)
```

### workaround

escape the hostname:

```
[**www\.richardianson\.com**](https://richardianson.com/)
```

**Comment by tripodsan** [comment]
btw, the serialization doesn't escape the hostname

```js
const mdast = root([
  paragraph([
    link('https://richardianson.com/', undefined, [
      strong([
        text('www.richardianson.com'),
      ])
    ]),
  ]),
]);

const doc = unified()
  .use(stringify)
  .use(gfm)
  .stringify(mdast);

console.log(doc);
```

gives:

```
[**www.richardianson.com**](https://richardianson.com/)
```

so, it's rather hard to handle this properly in the client. the only workaround is to move all formattings out of the link children.

**Comment by wooorm** [comment]
What GFM (well, github.com, because it’s not documented in GFM and doesn’t work like CM) seems to be doing here is rather complex... Take this markdown:

```markdown
**www.a.com**](b)
```

Yields:

**www.a.com**](b)

^ So, all the characters are valid in a URL. And the attention (strong) does not “break out” of the URL. Nor does the label end (`](b)`).

Whereas:

```markdown
[**www.a.com**](b)
```

Yields:

[**www.a.com**](b)

^ So, apparently, the URLs are parsed *after* the label end matches a label start. But before attention (`**`) is parsed? 🤔

**Comment by wooorm** [comment]
For serialization, [`link` and `image`](https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/blob/4c622a8548f59c64c38c8b9d7a8f8fc364ab428b/to-markdown.js#L2) might have to be removed, if I can’t think of anything else

**Comment by wooorm** [comment]
this should all be fixed with https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/commit/a2fac797b315885cf6e279eb7577f1db3a8562e4 btw!
