### ISSUE TITLE
Parse `www.` won't return positions 

### ISSUE THREAD

**Issue by ocavue** [syntax-tree/mdast-util-gfm-autolink-literal#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-gfm-autolink-literal@1.0.2

### Steps to reproduce

Run the following script: 

```js
import { fromMarkdown } from 'mdast-util-from-markdown';
import { gfmAutolinkLiteral } from 'micromark-extension-gfm-autolink-literal';
import { gfmAutolinkLiteralFromMarkdown } from 'mdast-util-gfm-autolink-literal';

function log(text) {
  let tree = fromMarkdown(text, {
    extensions: [gfmAutolinkLiteral],
    mdastExtensions: [gfmAutolinkLiteralFromMarkdown],
  });
  let tokens = tree.children[0].children;
  console.log(`parsed result for "${text}":`)
  console.dir(tokens, { depth: null });
}

log('www.example.com.');
log('www.');
```

This script will output the following content:

```js
parsed result for "www.example.com.":
[
  {
    type: 'link',
    title: null,
    url: 'http://www.example.com',
    children: [
      {
        type: 'text',
        value: 'www.example.com',
        position: {
          start: { line: 1, column: 1, offset: 0 },
          end: { line: 1, column: 16, offset: 15 }
        }
      }
    ],
    position: {
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 1, column: 16, offset: 15 }
    }
  },
  {
    type: 'text',
    value: '.',
    position: {
      start: { line: 1, column: 16, offset: 15 },
      end: { line: 1, column: 17, offset: 16 }
    }
  }
]
parsed result for "www.":
[
  {
    type: 'link',
    title: null,
    url: 'http://www',
    children: [ { type: 'text', value: 'www' } ]
  },
  { type: 'text', value: '.' }
]
```

### Expected behavior

Parsing links should return `text` and `link` tokens with `position` property.  

### Actual behavior

Parsing `www.` didn't return `position` property in the `text` token and `link` token. 

### Affected runtime and version

node@16.17.0

**Comment by ocavue** [comment]
It seems that [mdast-util-gfm-autolink-literal](https://github.com/syntax-tree/mdast-util-gfm-autolink-literal) use [mdast-util-find-and-replace](https://github.com/syntax-tree/mdast-util-find-and-replace) to handle `"www."`. I'm not sure if this this case is an expected limitation from `mdast-util-find-and-replace`.

**Comment by wooorm** [comment]
See https://github.com/remarkjs/remark-gfm/issues/16.
This is currently impossible and expected. GH does this as a transform afterwards too.

I’m currently working on a markdown parser in a different language. There I did implement it as a sort of transform still “on the parser”, which means positional info is there.
I am planning to at some point port these things back. But currently I think this is currently expected.

**Comment by ocavue** [comment]
Thanks for your explanation.

**Comment by wooorm** [comment]
Closing this for now. It’s currently expected. I will likely devise something in the future though!
